# Generated by Django 3.2.3 on 2021-09-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_chief',
            field=models.BooleanField(default=False),
        ),
    ]
