# Generated by Django 3.2.3 on 2021-09-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_chief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_chief',
        ),
    ]
