# Generated by Django 3.2.3 on 2021-09-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preferences', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.localisation')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('available', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preferences.stock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.supplier')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TreeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_down', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('maintenance_start_time', models.DateTimeField()),
                ('maintenance_end_tieme', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.equipement')),
                ('failed_piece', models.ManyToManyField(to='Assets.TreeStructure')),
                ('repair_piece', models.ManyToManyField(to='Assets.Tools')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Assets.supplier'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account'),
        ),
    ]
