# Generated by Django 3.2.3 on 2021-09-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0002_alter_supplier_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='tools',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
