# Generated by Django 3.2.3 on 2021-09-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0004_alter_supplier_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='available',
        ),
    ]
