# Generated by Django 3.2.3 on 2021-09-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0005_auto_20210915_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='maintenance_end_tieme',
            new_name='maintenance_end_time',
        ),
    ]
