# Generated by Django 3.2.3 on 2021-09-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0006_rename_maintenance_end_tieme_workorder_maintenance_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='is_down',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='failed_piece',
        ),
        migrations.AddField(
            model_name='workorder',
            name='failed_piece',
            field=models.CharField(default='fgdfgds', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='repair_piece',
        ),
        migrations.AddField(
            model_name='workorder',
            name='repair_piece',
            field=models.CharField(default='fgfdgdf', max_length=100),
            preserve_default=False,
        ),
    ]
