# Generated by Django 3.2.3 on 2021-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assets', '0007_auto_20210920_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='full_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
